import Head from 'next/head';
import Image from 'next/image';
import Nav from '../components/nav';
import styles from '../styles/awards.module.css';
import AwardImage from '../assets/images/award.jpg';

const Awards = () => {
  return (
    <div className={styles.container}>
        <Head>
            <title>Precious Eniayekan  </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

      <main className={styles.main}>
          <Nav />
          <div className={styles.image}>
              <Image src={AwardImage} alt='' height={400} width={600} />
          </div>
          <div className={styles.welcome}>
          </div>
      </main>
    </div>
  )
}

export default Awards;