import Head from 'next/head';
import NextImage from 'next/image';
import Nav from '../components/nav';
import styles from '../styles/marketing.module.css';
import MarketingImage from '../assets/images/techsis.jpg';

const Marketing = () => {
  return (
    <div className={styles.container}>
        <Head>
            <title>Precious Eniayekan  </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

      <main className={styles.main}>
          <Nav />
          <div className={styles.image}>
              <NextImage src={MarketingImage} alt='' height={500} width={500}/>
          </div>
          <div className={styles.welcome}>
          </div>
      </main>
    </div>
  )
}

export default Marketing;