import Head from 'next/head';
import Image from 'next/image';
import Nav from '../components/nav';
import styles from '../styles/tsi.module.css';
import RevenyImage from '../assets/images/reveny.jpg';

const Reveny = () => {
  return (
    <div className={styles.container}>
        <Head>
            <title>Precious Eniayekan  </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

      <main className={styles.main}>
          <Nav />
          <Image src={RevenyImage} alt='' height={400} width={400} className={styles.image}/>
          <div className={styles.welcome}>
          </div>
      </main>
    </div>
  )
}

export default Reveny;