import Head from 'next/head';
import Image from 'next/image';
import Nav from '../components/nav';
import styles from '../styles/revney.module.css';
import RevneyImage from '../assets/images/reveny.jpg';

const Revney = () => {
  return (
    <div className={styles.container}>
        <Head>
            <title>Precious Eniayekan  </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

      <main className={styles.main}>
          <Nav />
          <div className={styles.image}>
              <Image src={RevneyImage} alt='' height={500} width={700} />
          </div>
          <div className={styles.welcome}>
          </div>
      </main>
    </div>
  )
}

export default Revney;